#!/usr/bin/env python

import pygame
import random

MAX_STARS = 50

class Space:
    def __init__(self, destination):
        self.__layout = destination

        self.__maxx = self.__layout.get_rect().width
        self.__maxy = self.__layout.get_rect().height

        self.bg = pygame.image.load('data/playground.png')

        self.stars_spr = []
        self.stars_spr.append((pygame.image.load('data/star1.png'), 6, 8))
        self.stars_spr.append((pygame.image.load('data/star2.png'), 3, 5))
        self.stars_spr.append((pygame.image.load('data/star3.png'), 1, 2))

        self.stars = []
        for i in range(MAX_STARS):
            star = random.choice(self.stars_spr)
            self.stars.append((random.randint(0, self.__maxx),
                               random.randint(0, self.__maxy),
                               random.randint(star[1], star[2]),
                               star[0]))
            
    def update(self):
        self.__layout.blit(self.bg, (0, 0))

        for i in range(MAX_STARS):
            self.__layout.blit(self.stars[i][3],
                               (self.stars[i][0], self.stars[i][1]))
            self.stars[i] = (self.stars[i][0],
                            self.stars[i][1] + self.stars[i][2],
                            self.stars[i][2],
                            self.stars[i][3])
            if self.stars[i][1] > (self.__maxy + 10):
                star = random.choice(self.stars_spr)
                self.stars[i] = (random.randint(0, self.__maxx), -5,
                                 random.randint(star[1], star[2]),
                                 star[0])
                
class Player:
    def __init__(self, destination):
        self.__layout = destination

        self.ship = pygame.image.load('data/ship.png')

        self.__maxx = self.__layout.get_rect().width
        self.__maxy = self.__layout.get_rect().height

        self.x = int(self.__maxx - (self.ship.get_rect().width / 2) / 2)
        self.y = self.__maxy - self.ship.get_rect().height - 5

        self.__minpx = 0
        self.__maxpx = (self.__maxx - self.ship.get_rect().width)

        self.vx = 0
        self.max_v = 0

    def set_speed(self, vx):
        self.max_v = vx

    def update(self):
        if self.vx < self.max_v:
            self.vx += 1
        if self.vx > self.max_v:
            self.vx -= 1
        self.x += self.vx

        if self.x < self.__minpx:
            self.x = self.__minpx
        if self.x > self.__maxpx:
            self.x = self.__maxpx

        self.__layout.blit(self.ship, (self.x, self.y))

    def laser_pos(self):
        return (self.x + 30, self.y)

class PlayerShoot:
    def __init__(self, layout, position):
        self.__layout = layout
        self.shoot = pygame.image.load('data/shoot.png')

        self.x = position[0]
        self.y = position[1]

    def update(self):
        self.y = self.y - 10
        self.__layout.blit(self.shoot, (self.x, self.y))


class Game:
    def __init__(self, screen):
        self.__scr = screen

        self.__playground = pygame.image.load('data/playground.png')

        self.space = Space(self.__playground)
        self.player = Player(self.__playground)

        self.shoot_sound = pygame.mixer.Sound('data/shoot.wav')

        self.laser = None

        self.__scr.blit(pygame.image.load('data/background.png'), (0, 0))

    def run(self):

        while 1:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    return
                elif (event.type == pygame.KEYDOWN and
                      event.key == pygame.K_ESCAPE):
                    return
                elif (event.type == pygame.KEYDOWN and
                      event.key == pygame.K_LEFT):
                    self.player.set_speed(-4)
                elif (event.type == pygame.KEYDOWN and
                      event.key == pygame.K_RIGHT):
                    self.player.set_speed(4)
                elif ((event.type == pygame.KEYUP) and
                      (event.key == pygame.K_LEFT) and
                      (self.player.max_v == -4)):
                    self.player.set_speed(0)
                elif ((event.type == pygame.KEYUP) and
                      (event.key == pygame.K_RIGHT) and
                      (self.player.max_v == 4)):
                    self.player.set_speed(0)
                elif (event.type == pygame.KEYDOWN and
                      event.key == pygame.K_SPACE) and not self.laser:
                    self.shoot_sound.play()
                    self.laser = PlayerShoot(self.__playground,
                                             self.player.laser_pos())

            # Draw everything
            self.space.update()
            self.player.update()
            if not (self.laser is None):
                self.laser.update()
                if self.laser.y < -20:
                    self.laser = None
            self.__scr.blit(self.__playground, (28, 145))
            pygame.display.flip()

if __name__ == '__main__':
    pygame.init()
    screen = pygame.display.set_mode((1024, 768), pygame.FULLSCREEN)
    game = Game(screen)
    game.run()
